interface IActionTypes {
    SET_PRODUCTS: string,
    SELECTED_PRODUCTS: string,
    REMOVE_SELECTED_PRODUCTS: string
}

export const ActionTypes: IActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS"
}